[package]
name = "obs"
version = "0.1.0"
authors = ["Matt Coffin <mcoffin@qw-corp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[dependencies.obs-sys]
path = "../obs-sys"
